apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: compute-metrics
  namespace: airflow
spec:
  type: Scala
  mode: cluster
  sparkVersion: "3.5.1"
  image: compute_metrics:latest
  imagePullPolicy: Never
  mainClass: com.batchpipeline.metrics.Main
  mainApplicationFile: "local:///opt/app.jar"
  restartPolicy:
    type: Never
  driver:
    cores: 2
    coreLimit: "2"
    memory: "3g"
    serviceAccount: spark-operator-spark
    env:
      - name: CASSANDRA_HOST
        value: "cassandra"
      - name: CASSANDRA_PORT
        value: "9042"
    volumeMounts:
      - name: transformations
        mountPath: /opt/transformations
  executor:
    cores: 2
    coreLimit: "2"
    memory: "1g"
    env:
      - name: CASSANDRA_HOST
        value: "cassandra"
      - name: CASSANDRA_PORT
        value: "9042"
    volumeMounts:
      - name: transformations
        mountPath: /opt/transformations
  volumes:
    - name: transformations
      persistentVolumeClaim:
        claimName: metrics-pvc
